flutter_icons:
  android: true
  ios: true
  image_path: "config/.nt/images/appicon.png"
  remove_alpha_ios: true

  #  Because of bug in the package for adaptive icons which expand both images (foreground, background and zoom them in and cut edges), we need to prepare icons with padding thru
  #  https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html#foreground.type=image&foreground.space.trim=1&foreground.space.pad=0.24&foreColor=rgba(96%2C%20125%2C%20139%2C%200)&backColor=rgb(255%2C%20255%2C%20255)&crop=0&backgroundShape=square&effects=none&name=ic_launcher
  #  it is necessary to upload icon, then check there is padding 24% and download square version and use 1024 icon from folder as a adaptive icon
  #  until this issue will be resolved
  #  https://github.com/fluttercommunity/flutter_launcher_icons/issues/96
  adaptive_icon_background: "config/.nt/images/appicon-padding.png"
  adaptive_icon_foreground: "config/.nt/images/appicon-padding.png"