name: nt_flutter_standalone
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 5.1.11+5111

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # 0.16.0 extended with custom methods to set layer visibility
  mapbox_gl:
    git:
      url: https://github.com/specure/flutter-mapbox-gl.git
      ref: main

  cell_info:
    git:
      url: https://github.com/specure/FlutterCellInfo.git
      ref: updates_and_fixes

  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  sprintf: ^6.0.0
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  fl_chart: ^0.41.0
  permission_handler: ^8.1.4+2
  flutter_svg: ^1.0.3
  flutter_dotenv: 5.0.2
  dio: ^4.0.4
  intl: 0.17.0
  json_annotation: ^4.4.0
  shared_preferences: ^2.0.8
  lazy_load_scrollview: 1.3.0
  connectivity_plus: ^2.2.0
  device_info_plus: ^3.2.1
  wifi_iot: ^0.3.18
  syncfusion_flutter_charts: ^19.4.48+1
  uuid: 3.0.5
  geocoding: ^2.0.1
  package_info_plus: ^1.3.0
  flutter_markdown: ^0.6.9
  flutter_html:
  firebase_core_platform_interface: 4.4.1
  firebase_core: 1.18.0
  firebase_analytics: 9.1.10
  flutter_native_splash: ^2.1.5
  url_launcher: 6.1.0
  in_app_review: ^2.0.6
  sentry_flutter: ^6.19.0
  geolocator: ^9.0.1
  clock: ^1.1.0
  pie_chart: ^5.3.2
  network_info_plus: ^2.1.4+1
  html: ^0.15.1
  app_settings: ^4.2.0

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.4

  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.2
  mockito: ^5.0.17
  flutter_launcher_icons: ^0.9.3
  flutter_oss_licenses: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/icons/
    - config/.nt/
    - config/.nt/images/
    - config/.nt/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
