// Mocks generated by Mockito 5.4.4 from annotations
// in nt_flutter_standalone/test/net-neutrality/unit-tests/net-neutrality-measurement-service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:connectivity_plus/connectivity_plus.dart' as _i11;
import 'package:flutter/services.dart' as _i2;
import 'package:flutter_bloc/flutter_bloc.dart' as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nt_flutter_standalone/core/models/error-handler.dart' as _i9;
import 'package:nt_flutter_standalone/modules/measurements/services/network.service.dart'
    as _i10;
import 'package:nt_flutter_standalone/modules/net-neutrality/constants/net-neutrality-details.dart'
    as _i12;
import 'package:nt_flutter_standalone/modules/net-neutrality/models/dns-net-neutrality-settings-item.dart'
    as _i7;
import 'package:nt_flutter_standalone/modules/net-neutrality/models/dns-result.dart'
    as _i6;
import 'package:nt_flutter_standalone/modules/net-neutrality/models/net-neutrality-history-item.dart'
    as _i13;
import 'package:nt_flutter_standalone/modules/net-neutrality/services/dns-test.service.dart'
    as _i4;
import 'package:nt_flutter_standalone/modules/net-neutrality/store/net-neutrality.cubit.dart'
    as _i8;
import 'package:nt_flutter_standalone/modules/net-neutrality/store/net-neutrality.state.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMethodChannel_0 extends _i1.SmartFake implements _i2.MethodChannel {
  _FakeMethodChannel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNetNeutralityState_1 extends _i1.SmartFake
    implements _i3.NetNeutralityState {
  _FakeNetNeutralityState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DnsTestService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDnsTestService extends _i1.Mock implements _i4.DnsTestService {
  MockDnsTestService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MethodChannel get channel => (super.noSuchMethod(
        Invocation.getter(#channel),
        returnValue: _FakeMethodChannel_0(
          this,
          Invocation.getter(#channel),
        ),
      ) as _i2.MethodChannel);

  @override
  _i5.Future<_i6.DnsResult?> execute(
          _i7.DnsNetNeutralitySettingsItem? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [params],
        ),
        returnValue: _i5.Future<_i6.DnsResult?>.value(),
      ) as _i5.Future<_i6.DnsResult?>);
}

/// A class which mocks [NetNeutralityCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetNeutralityCubitCalls extends _i1.Mock
    implements _i8.NetNeutralityCubit {
  @override
  set errorHandler(_i9.ErrorHandler? _errorHandler) => super.noSuchMethod(
        Invocation.setter(
          #errorHandler,
          _errorHandler,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set connectivityChangesHandler(
          _i10.ConnectivityChangesHandler? _connectivityChangesHandler) =>
      super.noSuchMethod(
        Invocation.setter(
          #connectivityChangesHandler,
          _connectivityChangesHandler,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.NetNeutralityState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeNetNeutralityState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeNetNeutralityState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.NetNeutralityState);

  @override
  _i5.Stream<_i3.NetNeutralityState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i3.NetNeutralityState>.empty(),
        returnValueForMissingStub: _i5.Stream<_i3.NetNeutralityState>.empty(),
      ) as _i5.Stream<_i3.NetNeutralityState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Future<dynamic> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i5.Future<dynamic>.value(),
        returnValueForMissingStub: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  dynamic updateConnectivity(_i11.ConnectivityResult? connectivity) =>
      super.noSuchMethod(
        Invocation.method(
          #updateConnectivity,
          [connectivity],
        ),
        returnValueForMissingStub: null,
      );

  @override
  dynamic openResultDetails(
    _i12.NetNeutralityDetailsConfig? detailsConfig,
    List<_i13.NetNeutralityHistoryItem>? results,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #openResultDetails,
          [
            detailsConfig,
            results,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> loadResults(String? openTestUuid) => (super.noSuchMethod(
        Invocation.method(
          #loadResults,
          [openTestUuid],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void emit(_i3.NetNeutralityState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i14.Change<_i3.NetNeutralityState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
